package com.raspberrypi.fermzilla.rPiMSMonitor.mongodb;

import lombok.*;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;
import java.util.Objects;
import java.util.Set;

@Document
@RequiredArgsConstructor
public class BatchPojo {

    @Id
    private String batchId;

    @ToString.Exclude
    private Set<Temperatures> temperatures;

    //Autogenerated below

    public String getBatchId() {
        return batchId;
    }

    public void setBatchId(String batchId) {
        this.batchId = batchId;
    }

    public Set<Temperatures> getTemperatures() {
        return temperatures;
    }

    public void setTemperatures(Set<Temperatures> temperatures) {
        this.temperatures = temperatures;
    }

    @Override
    public String toString() {
        return "BatchPojo{" +
                "batchId=" + batchId +
                ", temperatures=" + temperatures +
                '}';
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        BatchPojo batchPojo = (BatchPojo) o;
        return batchId.equals(batchPojo.batchId) && temperatures.equals(batchPojo.temperatures);
    }

    @Override
    public int hashCode() {
        return Objects.hash(batchId, temperatures);
    }
}
