package com.raspberrypi.fermzilla.rPiMSMonitor.mongodb;

import lombok.RequiredArgsConstructor;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

import java.util.Objects;


@Document
@RequiredArgsConstructor
public class Temperatures {
    @Id
    private String id;

    private Double temps;

    private BatchPojo batchPojo;

    //Autogenerated below

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public Double getTemps() {
        return temps;
    }

    public void setTemps(Double temps) {
        this.temps = temps;
    }

    public BatchPojo getBatchPojo() {
        return batchPojo;
    }

    public void setBatchPojo(BatchPojo batchPojo) {
        this.batchPojo = batchPojo;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Temperatures that = (Temperatures) o;
        return id.equals(that.id) && temps.equals(that.temps) && batchPojo.equals(that.batchPojo);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, temps, batchPojo);
    }

    @Override
    public String toString() {
        return "Temperatures{" +
                "id=" + id +
                ", temps=" + temps +
                ", batchPojo=" + batchPojo +
                '}';
    }
}
